### ISSUE TITLE
Please add an example/guide to change keyboard layout

### ISSUE THREAD

**Issue by schneekluth** [adafruit/Adafruit_CircuitPython_MacroPad#41]
I have just received my Macropad and having trouble changing the default keyboard layout. The docs only refer to the guide from [Neradoc](https://github.com/Neradoc/Circuitpython_Keyboard_Layouts) that are not very helpful for a beginner. I have tried to change to the German Layout but cannot get it to work. I think a detailled example or a step by step guide would be helpful.

**UPDATE:**
Got it to work. Found this PR but it is rather not intuitive: https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/pull/17

**Comment by Neradoc** [comment]
There is an example, there is no guide yet though:
https://github.com/adafruit/Adafruit_CircuitPython_MacroPad/blob/main/examples/macropad_keyboard_layout.py

I've added information on how to use it with the Hotkeys code too.
https://github.com/Neradoc/Circuitpython_Keyboard_Layouts/blob/main/README-MACROPAD.md

**Comment by schneekluth** [comment]
Thank you!
