### ISSUE TITLE
Convert `.show()` to `.root_group =` for CircuitPython 9

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_MacroPad#48]

**Comment by prcutler** [comment]
The file `macropad_grid_layout.py` (https://github.com/adafruit/Adafruit_CircuitPython_MacroPad/blob/main/examples/macropad_grid_layout.py) has this code in it:

`macropad.display.show(main_group)` on line 17

I assume this should not be updated with the `root_group` fix for CP9 as that functionality is from the MacroPad module?

**Comment by FoamyGuy** [comment]
@prcutler it should be changed. That usage is on the macropad class which isn't what changed so your instinct does make sense. But the macropad actually has a normal display object on it that is being accessed so it will use the new API as well. Here is the code inside of Macropad class where it sets up the display that is being used: https://github.com/adafruit/Adafruit_CircuitPython_MacroPad/blob/6490c5d69e8fe2e4e2e176ec0facd199e8d971e4/adafruit_macropad.py#L292-L294
