### ISSUE TITLE
Looking for an example of using the TX1 and RX1 pins available on the STEMMA QT connection

### ISSUE THREAD

**Issue by allordacia** [adafruit/Adafruit_CircuitPython_MacroPad#55]
I am trying to use TX1 and RX1 from the STEMMA QT cable but for the life of me cannot figure out the correct way to set them up to be UART pins as opposed the SDA SCL pins. Can you provide me with an example of how to do this?

**Comment by allordacia** [comment]
Found what I was looking for, disregard.

**Comment by natcl** [comment]
Curious about this, what was the solution?
